In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pt
import seaborn as sns

In [84]:
# all data import
customers= pd.read_csv(r"D:\Python Data\relational dataset\customers.csv")
orders = pd.read_csv(r"D:\Python Data\relational dataset\orders.csv")
payments = pd.read_csv(r"D:\Python Data\relational dataset\payments.csv")
products = pd.read_csv(r"D:\Python Data\relational dataset\products.csv")

In [91]:
#viewed all columns of all files to see common columns
print(customers.columns,
orders.columns,
payments.columns,products.columns)

Index(['CustomerID', 'Age', 'City', 'SignupDate', 'CustomerSegment'], dtype='object') Index(['OrderID', 'CustomerID', 'OrderDate', 'ProductID', 'Quantity',
       'Discount', 'PaymentMethod', 'Status'],
      dtype='object') Index(['PaymentID', 'OrderID', 'PaymentDate', 'PaymentStatus'], dtype='object') Index(['ProductID', 'ProductName', 'Category', 'UnitPrice'], dtype='object')

In [94]:
#combining to make single file
df = orders.merge(customers,on='CustomerID', how="left")

In [95]:
df = df.merge(products,on='ProductID',how="left")

In [97]:
df = df.merge(payments,on='OrderID',how="left")

In [98]:
df.columns

Index(['OrderID', 'CustomerID', 'OrderDate', 'ProductID', 'Quantity',
       'Discount', 'PaymentMethod', 'Status', 'Age', 'City', 'SignupDate',
       'CustomerSegment', 'ProductName', 'Category', 'UnitPrice', 'PaymentID',
       'PaymentDate', 'PaymentStatus'],
      dtype='object')

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50120 entries, 0 to 50119
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          50120 non-null  int64
 1   CustomerID       50120 non-null  int64
 2   OrderDate        50085 non-null  object
 3   ProductID        50120 non-null  int64
 4   Quantity         50040 non-null  float64
 5   Discount         49899 non-null  float64
 6   PaymentMethod    49668 non-null  object
 7   Status           50120 non-null  object
 8   Age              49202 non-null  float64
 9   City             49452 non-null  object
 10  SignupDate       50090 non-null  object
 11  CustomerSegment  50090 non-null  object
 12  ProductName      50120 non-null  object
 13  Category         50120 non-null  object
 14  UnitPrice        50120 non-null  float64
 15  PaymentID        50120 non-null  int64
 16  PaymentDate      50085 non-null  object
 17  PaymentStatus    50120 non-null  object
dtypes: float64(4), int64(4), object(10)
memory usage: 6.9+ MB

In [10]:
df.describe()

,Customer_Age,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Delivery_Days,Customer_Rating,Inventory_Level,Order_Year
count,17827.000000,18045.000000,18045.000000,18045.000000,18045.000000,18045.000000,18045.000000,17883.000000,14610.000000,17847.000000,18045.000000
mean,38.916924,2.127127,232.685633,6.256858,457.309027,366.001156,91.404131,2.262204,3.985969,70.257914,2023.566417
std,10.727357,1.786212,294.208022,6.881178,856.597181,705.866738,167.827883,2.321656,1.008422,22.042609,1.118744
min,4.000000,-3.000000,21.390000,0.000000,16.680000,12.170000,-299.310000,0.000000,1.000000,0.000000,2022.000000
25%,32.000000,1.000000,53.380000,0.000000,78.530000,56.120000,19.480000,0.000000,4.000000,55.000000,2023.000000
50%,39.000000,2.000000,99.870000,5.000000,168.810000,122.300000,40.190000,1.000000,4.000000,70.000000,2024.000000
75%,46.000000,3.000000,285.580000,10.000000,472.450000,376.020000,93.270000,4.000000,5.000000,85.000000,2025.000000
max,112.000000,11.000000,1425.090000,110.000000,14303.070000,10791.000000,3512.080000,10.000000,5.000000,157.000000,2025.000000

In [100]:
df.shape

(50120, 18)

In [101]:
df.isnull().sum()

OrderID              0
CustomerID           0
OrderDate           35
ProductID            0
Quantity            80
Discount           221
PaymentMethod      452
Status               0
Age                918
City               668
SignupDate          30
CustomerSegment     30
ProductName          0
Category             0
UnitPrice            0
PaymentID            0
PaymentDate         35
PaymentStatus        0
dtype: int64

In [102]:
#Identifing missing values
total_null=df.isnull().sum()
(total_null>1).sum()
only_null= total_null[total_null>1].sort_values(ascending=False)
only_null

Age                918
City               668
PaymentMethod      452
Discount           221
Quantity            80
OrderDate           35
PaymentDate         35
SignupDate          30
CustomerSegment     30
dtype: int64

In [104]:
numeric= df.select_dtypes(include='number').columns
categorical = df.select_dtypes(include='object').columns
print("numeric=",(numeric),"\n\n\ncategorical=",(categorical))

numeric= Index(['OrderID', 'CustomerID', 'ProductID', 'Quantity', 'Discount', 'Age',
       'UnitPrice', 'PaymentID'],
      dtype='object')


categorical= Index(['OrderDate', 'PaymentMethod', 'Status', 'City', 'SignupDate',
       'CustomerSegment', 'ProductName', 'Category', 'PaymentDate',
       'PaymentStatus'],
      dtype='object')

In [105]:
# Filling numerical nulls
df["Quantity"] = df["Quantity"].fillna(
    df["Quantity"].median()
)

In [ ]:
df["Discount"] = df["Discount"].fillna(
    df["Discount"].median()
)

In [106]:
df["Age"] = df["Age"].fillna(
    df["Age"].median()
)

In [110]:
df.isnull().sum().sort_values(ascending=False)

City               668
PaymentMethod      452
Discount           221
OrderDate           35
PaymentDate         35
SignupDate          30
CustomerSegment     30
OrderID              0
CustomerID           0
Quantity             0
Age                  0
Status               0
ProductID            0
ProductName          0
Category             0
UnitPrice            0
PaymentID            0
PaymentStatus        0
dtype: int64

In [114]:
# Filling categorical nulls
df["City"] = df["City"].fillna('unknown')
df["PaymentMethod"] = df["PaymentMethod"].fillna('unknown')
df["OrderDate"] = df["OrderDate"].fillna('unknown')
df["PaymentDate"] = df["PaymentDate"].fillna('unknown')
df["SignupDate"] = df["SignupDate"].fillna('unknown')
df["CustomerSegment"] = df["City"].fillna('CustomerSegment')

In [115]:
df["Discount"] = df["Discount"].fillna(0)

In [116]:
df.isnull().sum()

OrderID            0
CustomerID         0
OrderDate          0
ProductID          0
Quantity           0
Discount           0
PaymentMethod      0
Status             0
Age                0
City               0
SignupDate         0
CustomerSegment    0
ProductName        0
Category           0
UnitPrice          0
PaymentID          0
PaymentDate        0
PaymentStatus      0
dtype: int64

In [117]:
df.head(10)

,OrderID,CustomerID,OrderDate,ProductID,Quantity,Discount,PaymentMethod,Status,Age,City,SignupDate,CustomerSegment,ProductName,Category,UnitPrice,PaymentID,PaymentDate,PaymentStatus
0,500001,103695,2025-08-28,2003,4.0,0.10,Gateway,Completed,36.0,Qom,2024-03-05,Qom,USB-C Cable,Accessories,9.0,800001,2025-08-28,Paid
1,500002,107935,2024-05-31,2014,1.0,0.10,Wallet,Completed,49.0,Kerman,2025-06-04,Kerman,Backpack,Accessories,42.0,800002,2024-05-31,Paid
2,500003,105141,2025-08-10,2002,1.0,0.20,CardToCard,Completed,36.0,Tehran,2025-10-19,Tehran,Mechanical Keyboard,Electronics,62.0,800003,2025-08-10,Paid
3,500004,108780,2024-10-11,2012,1.0,0.10,Gateway,Completed,45.0,Shiraz,2023-12-07,Shiraz,Office Chair,Home Office,180.0,800004,2024-10-11,Paid
4,500005,101187,2024-02-19,2008,2.0,0.00,Gateway,Completed,24.0,Karaj,2023-12-02,Karaj,Phone Case,Accessories,14.0,800005,2024-02-19,Paid
5,500006,105545,2024-07-16,2011,4.0,0.00,Gateway,Returned,28.0,Tehran,2024-08-07,Tehran,Desk Lamp,Home Office,32.0,800006,2024-07-16,Failed
6,500007,106418,2025-10-15,2017,1.0,0.05,Wallet,Completed,23.0,Isfahan,2023-03-09,Isfahan,HDMI Cable,Accessories,11.0,800007,2025-10-15,Paid
7,500008,108755,2024-12-03,2014,1.0,0.00,Gateway,Completed,41.0,Mashhad,2025-11-20,Mashhad,Backpack,Accessories,42.0,800008,2024-12-03,Paid
8,500009,105133,2025-04-15,2004,1.0,0.10,Gateway,Completed,40.0,Isfahan,2025-05-04,Isfahan,Power Bank,Electronics,35.0,800009,2025-04-15,Paid
9,500010,103111,2024-04-28,2014,2.0,0.05,Gateway,Cancelled,43.0,Mashhad,2024-06-20,Mashhad,Backpack,Accessories,42.0,800010,2024-04-28,Paid

In [119]:
# duplicate records
df.duplicated().sum()

np.int64(120)

In [120]:
duplicates = df[df.duplicated()]

duplicates.head(10)

,OrderID,CustomerID,OrderDate,ProductID,Quantity,Discount,PaymentMethod,Status,Age,City,SignupDate,CustomerSegment,ProductName,Category,UnitPrice,PaymentID,PaymentDate,PaymentStatus
50000,533554,102136,2025-09-11,2007,1.0,0.00,Gateway,Completed,50.0,Tabriz,2025-06-27,Tabriz,Headphones,Electronics,75.0,833554,2025-09-11,Paid
50001,509428,103702,2026-06-15,2003,2.0,0.10,CardToCard,Completed,29.0,Shiraz,2025-04-29,Shiraz,USB-C Cable,Accessories,9.0,809428,2026-06-15,Paid
50002,500200,104768,2025-08-03,2008,2.0,0.10,CardToCard,Completed,18.0,Tabriz,2025-05-29,Tabriz,Phone Case,Accessories,14.0,800200,2025-08-03,Paid
50003,512448,103977,2025-09-25,2011,1.0,0.00,Gateway,Completed,48.0,Tehran,2024-10-13,Tehran,Desk Lamp,Home Office,32.0,812448,2025-09-25,Paid
50004,539490,105856,2026-06-13,2001,1.0,0.20,CardToCard,Completed,46.0,Tehran,2025-10-01,Tehran,Wireless Mouse,Electronics,18.0,839490,2026-06-13,Paid
50005,542725,108045,2026-05-15,2007,3.0,0.00,CardToCard,Completed,37.0,Kerman,2024-02-10,Kerman,Headphones,Electronics,75.0,842725,2026-05-15,Paid
50006,510823,100899,2025-05-31,2003,2.0,0.10,Gateway,Completed,21.0,Shiraz,2024-02-13,Shiraz,USB-C Cable,Accessories,9.0,810823,2025-05-31,Paid
50007,549499,101941,2024-12-29,2005,1.0,0.00,Gateway,Completed,25.0,Karaj,2024-07-05,Karaj,Laptop Stand,Accessories,28.0,849499,2024-12-29,Paid
50008,504145,100289,2025-06-03,2004,1.0,0.05,CardToCard,Completed,44.0,Mashhad,2024-06-01,Mashhad,Power Bank,Electronics,35.0,804145,2025-06-03,Paid
50009,536959,107644,2025-02-05,2003,1.0,0.00,Gateway,Completed,48.0,Mashhad,2024-11-23,Mashhad,USB-C Cable,Accessories,9.0,836959,2025-02-05,Paid

In [121]:
df[df.duplicated(keep=False)]

,OrderID,CustomerID,OrderDate,ProductID,Quantity,Discount,PaymentMethod,Status,Age,City,SignupDate,CustomerSegment,ProductName,Category,UnitPrice,PaymentID,PaymentDate,PaymentStatus
199,500200,104768,2025-08-03,2008,2.0,0.10,CardToCard,Completed,18.0,Tabriz,2025-05-29,Tabriz,Phone Case,Accessories,14.0,800200,2025-08-03,Paid
725,500726,102977,2025-11-26,2013,2.0,0.10,Wallet,Returned,41.0,Ahvaz,2024-08-25,Ahvaz,Notebook,Stationery,7.0,800726,2025-11-26,Paid
821,500822,100897,2026-01-03,2003,1.0,0.00,Gateway,Completed,42.0,Tehran,2024-03-09,Tehran,USB-C Cable,Accessories,9.0,800822,2026-01-03,Paid
1414,501415,108793,2025-02-28,2004,1.0,0.10,Wallet,Completed,47.0,Tehran,2024-09-25,Tehran,Power Bank,Electronics,35.0,801415,2025-02-28,Paid
1812,501813,108688,2025-12-20,2014,2.0,0.10,unknown,Completed,29.0,Mashhad,2025-08-05,Mashhad,Backpack,Accessories,42.0,801813,2025-12-20,Paid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50115,546916,106069,2024-11-08,2003,1.0,0.10,CardToCard,Completed,25.0,Isfahan,2024-05-15,Isfahan,USB-C Cable,Accessories,9.0,846916,2024-11-08,Paid
50116,509802,107180,2024-09-19,2012,1.0,0.10,CardToCard,Completed,32.0,tehran,2023-01-06,tehran,Office Chair,Home Office,180.0,809802,2024-09-19,Paid
50117,538801,109723,2025-02-19,2006,2.0,0.05,Wallet,Completed,23.0,Karaj,2023-10-20,Karaj,Webcam,Electronics,48.0,838801,2025-02-19,Paid
50118,524670,108719,2025-08-08,2013,1.0,0.05,Gateway,Completed,48.0,Tabriz,2023-09-09,Tabriz,Notebook,Stationery,7.0,824670,2025-08-08,Paid
50119,544234,106789,2024-04-03,2003,1.0,0.00,Gateway,Completed,29.0,Karaj,2025-05-06,Karaj,USB-C Cable,Accessories,9.0,844234,2024-04-03,Paid

In [122]:
df = df.drop_duplicates()

In [123]:
df.head()

,OrderID,CustomerID,OrderDate,ProductID,Quantity,Discount,PaymentMethod,Status,Age,City,SignupDate,CustomerSegment,ProductName,Category,UnitPrice,PaymentID,PaymentDate,PaymentStatus
0,500001,103695,2025-08-28,2003,4.0,0.1,Gateway,Completed,36.0,Qom,2024-03-05,Qom,USB-C Cable,Accessories,9.0,800001,2025-08-28,Paid
1,500002,107935,2024-05-31,2014,1.0,0.1,Wallet,Completed,49.0,Kerman,2025-06-04,Kerman,Backpack,Accessories,42.0,800002,2024-05-31,Paid
2,500003,105141,2025-08-10,2002,1.0,0.2,CardToCard,Completed,36.0,Tehran,2025-10-19,Tehran,Mechanical Keyboard,Electronics,62.0,800003,2025-08-10,Paid
3,500004,108780,2024-10-11,2012,1.0,0.1,Gateway,Completed,45.0,Shiraz,2023-12-07,Shiraz,Office Chair,Home Office,180.0,800004,2024-10-11,Paid
4,500005,101187,2024-02-19,2008,2.0,0.0,Gateway,Completed,24.0,Karaj,2023-12-02,Karaj,Phone Case,Accessories,14.0,800005,2024-02-19,Paid

In [125]:
df.shape

(50000, 18)

In [127]:
#identifing incorrect datatypes
df.dtypes

OrderID              int64
CustomerID           int64
OrderDate           object
ProductID            int64
Quantity           float64
Discount           float64
PaymentMethod       object
Status              object
Age                float64
City                object
SignupDate          object
CustomerSegment     object
ProductName         object
Category            object
UnitPrice          float64
PaymentID            int64
PaymentDate         object
PaymentStatus       object
dtype: object

In [130]:
df["Age"] = df["Age"].astype("int64")

C:\Users\owner\AppData\Local\Temp\ipykernel_3268\885879307.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].astype("int64")

In [131]:
 #Making an independent copy
df = df.copy()
df["Age"] = df["Age"].astype("int64")
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50000 entries, 0 to 49999
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          50000 non-null  int64
 1   CustomerID       50000 non-null  int64
 2   OrderDate        50000 non-null  object
 3   ProductID        50000 non-null  int64
 4   Quantity         50000 non-null  float64
 5   Discount         50000 non-null  float64
 6   PaymentMethod    50000 non-null  object
 7   Status           50000 non-null  object
 8   Age              50000 non-null  int64
 9   City             50000 non-null  object
 10  SignupDate       50000 non-null  object
 11  CustomerSegment  50000 non-null  object
 12  ProductName      50000 non-null  object
 13  Category         50000 non-null  object
 14  UnitPrice        50000 non-null  float64
 15  PaymentID        50000 non-null  int64
 16  PaymentDate      50000 non-null  object
 17  PaymentStatus    50000 non-null  object
dtypes: float64(3), int64(5), object(10)
memory usage: 7.2+ MB

In [133]:
#handling inconsistant
df["Age"].head()

0    36
1    49
2    36
3    45
4    24
Name: Age, dtype: int64

In [138]:
agelow = df[df["Age"] < 0]

In [141]:
agelow

Empty DataFrame
Columns: [OrderID, CustomerID, OrderDate, ProductID, Quantity, Discount, PaymentMethod, Status, Age, City, SignupDate, CustomerSegment, ProductName, Category, UnitPrice, PaymentID, PaymentDate, PaymentStatus]
Index: []

In [139]:
agehigh = df[df["Age"] > 110]

In [140]:
agehigh

Empty DataFrame
Columns: [OrderID, CustomerID, OrderDate, ProductID, Quantity, Discount, PaymentMethod, Status, Age, City, SignupDate, CustomerSegment, ProductName, Category, UnitPrice, PaymentID, PaymentDate, PaymentStatus]
Index: []

In [142]:
df.to_csv("cleaned_dataset.csv", index=False)

In [143]:
import os

print(os.getcwd())

C:\Users\owner